<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <Version>0.2.16</Version>
    <ValheimDir Condition="'$(ValheimDir)' == ''">/home/deck/.local/share/Steam/steamapps/common/Valheim</ValheimDir>
  </PropertyGroup>
  <Import Project="Environment.props" Condition="Exists('Environment.props')" />
</Project>
