using System.Reflection;
using Helmsman;
using UnityEngine;
int checks=0;
void Check(bool yes,string label){if(!yes)throw new Exception("FAIL: "+label);checks++;Console.WriteLine("PASS: "+label);}
var player=new GameObject().AddComponent<Player>();Player.m_localPlayer=player;
var shipObject=new GameObject();var ship=shipObject.AddComponent<Ship>();ship.m_floatCollider=shipObject.AddComponent<BoxCollider>();
var shipView=shipObject.AddComponent<ZNetView>();
Container Hold(){var go=new GameObject();go.transform.SetParent(ship.transform);var c=go.AddComponent<Container>();c.m_rootObjectOverride=shipView;return c;}
var hold=Hold();
var stone=new GameObject(){name="Stone"};stone.AddComponent<ItemDrop>().m_itemData.m_dropPrefab=stone;
var rockObject=new GameObject(){name="rock_test"};rockObject.transform.localPosition=new(0,0,8);var rockView=rockObject.AddComponent<ZNetView>();var rock=rockObject.AddComponent<MineRock>();rock.name="rock_test";rock.m_dropItems=new();rock.m_dropItems.m_drops.Add(new(){m_item=stone});var obstacle=rockObject.AddComponent<BoxCollider>();
RockClearResult Clear(float speed=0,bool ready=true)=>RockClearing.TryClear(ship,player,obstacle,speed,ready,out _);
Check(Clear(2)==RockClearResult.Waiting&&NativeRock.Hits==0,"Moving boat brakes before clearing");
Check(Clear(0,false)==RockClearResult.Waiting&&NativeRock.Hits==0,"Cooldown prevents duplicate rock hits");
Check(Clear()==RockClearResult.Cleared&&hold.Inventory.Items.Sum(i=>i.m_stack)==1,"Native rock stone enters ship inventory");
Check(NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed&&hold.Inventory.Items[0].m_cheated,"Pickup removes world drop and preserves native metadata");
Check(!RockCargo.Store(ship,player,NativeRock.LastDrop)&&hold.Inventory.Items.Sum(i=>i.m_stack)==1,"Delayed drop destruction cannot duplicate pickup");
hold.Inventory.Items[0].m_stack=50;
Check(Clear()==RockClearResult.Cleared&&!NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed,"Full cargo keeps clearing and leaves excess stone in world");
Check(hold.Inventory.Items.Sum(i=>i.m_stack)==50,"Full cargo neither deletes nor fabricates resources");
var second=Hold();Check(Clear()==RockClearResult.Cleared&&second.Inventory.Items.Count==1,"Collection uses another available ship hold");
second.InUse=true;Clear();Check(!NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed,"Open cargo hold is not changed by pickup");second.InUse=false;
shipView.Data.InUse=1;Clear();Check(!NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed,"Remote inventory-in-use lock is honored");shipView.Data.InUse=0;
second.Access=false;Clear();Check(!NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed,"Private cargo access is honored");second.Access=true;
var scope=second.gameObject.AddComponent<ShipHoldScope>();scope.MigrationBlocked=true;Clear();Check(!NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed,"Unmigrated cargo is never overwritten");scope.MigrationBlocked=false;
second.Inventory.FailPartial=true;int before=second.Inventory.Items.Sum(i=>i.m_stack);Clear();Check(second.Inventory.Items.Sum(i=>i.m_stack)==before&&!NativeRock.LastDrop.GetComponent<ZNetView>().Destroyed,"Partial add failure rolls back and leaves stone available");second.Inventory.FailPartial=false;
var delayed=new GameObject().AddComponent<ItemDrop>();var delayedView=delayed.gameObject.AddComponent<ZNetView>();delayedView.FailDestroy=true;delayed.m_itemData=stone.GetComponent<ItemDrop>().m_itemData.Clone();
Check(RockCargo.Store(ship,player,delayed)&&delayed.m_itemData.m_stack==0&&delayedView.Data.Stack==0,"Delayed network destruction leaves no collectible duplicate stone");
PrivateArea.Allowed=false;int hits=NativeRock.Hits;Check(Clear()==RockClearResult.Blocked&&NativeRock.Hits==hits,"Protected rock is not damaged");PrivateArea.Allowed=true;
rockView.Owner=false;Check(Clear()==RockClearResult.Blocked&&NativeRock.Hits==hits,"Remote-owned rock is not damaged or forcibly claimed");rockView.Owner=true;
ship.Owner=false;Check(Clear()==RockClearResult.NotApplicable,"Non-owner cannot clear or collect");ship.Owner=true;
ship.Aboard=false;Check(Clear()==RockClearResult.NotApplicable,"Player must remain aboard");ship.Aboard=true;
ship.m_shipControlls.User=true;Check(Clear()==RockClearResult.NotApplicable,"Manual helm takeover disables rock clearing");ship.m_shipControlls.User=false;
rockObject.transform.localPosition=new(0,0,10);hits=NativeRock.Hits;Check(Clear()==RockClearResult.Waiting&&NativeRock.Hits==hits,"Karve slows without clearing beyond roughly 9 m reach");rockObject.transform.localPosition=new(0,0,8);
var ore=new GameObject(){name="CopperOre"};ore.AddComponent<ItemDrop>();rock.m_dropItems.m_drops.Add(new(){m_item=ore});Check(Clear()==RockClearResult.NotApplicable,"Mixed stone and ore deposit is not cleared");rock.m_dropItems.m_drops.RemoveAt(1);
rock.name="dungeon_stone";Check(Clear()==RockClearResult.NotApplicable,"Non-rock location prop is not cleared");rock.name="rock_test";
NativeRock.FailAfterDrop=true;before=second.Inventory.Items.Sum(i=>i.m_stack);Check(Clear()==RockClearResult.Blocked&&second.Inventory.Items.Sum(i=>i.m_stack)==before+1,"Native failure still preserves already-created resources");NativeRock.FailAfterDrop=false;
var unrelated=new GameObject().AddComponent<ItemDrop>();unrelated.m_itemData=stone.GetComponent<ItemDrop>().m_itemData.Clone();before=second.Inventory.Items.Sum(i=>i.m_stack);RockClearing.Capture(unrelated);Check(second.Inventory.Items.Sum(i=>i.m_stack)==before,"Unrelated dropped items are never swept into cargo");
rockObject.AddComponent<Piece>();Check(Clear()==RockClearResult.NotApplicable,"Player-built piece is never cleared");
var voyage=shipObject.AddComponent<Voyage>();voyage.Ship=ship;Plugin.Instance.Voyage=voyage;
var fishObject=new GameObject();fishObject.AddComponent<Fish>();var fishCollider=fishObject.AddComponent<BoxCollider>();var otherBoat=new GameObject().AddComponent<BoxCollider>();var rockCollider=new GameObject().AddComponent<BoxCollider>();
Physics.Nearby=new[]{fishCollider,rockCollider,otherBoat};FishCollisionPass.UpdateFor(ship,true);var pass=ship.GetComponent<FishCollisionPass>();pass.Refresh();
Check(Physics.GetIgnoreCollision(ship.m_floatCollider,fishCollider),"Fish-hull collision is ignored during active mode");
Check(!Physics.GetIgnoreCollision(ship.m_floatCollider,rockCollider)&&!Physics.GetIgnoreCollision(ship.m_floatCollider,otherBoat),"Rocks and other boats retain normal collisions");
pass.Restore();Check(!Physics.GetIgnoreCollision(ship.m_floatCollider,fishCollider),"Mode cleanup restores changed collision pairs");
Physics.IgnoreCollision(ship.m_floatCollider,fishCollider,true);pass.Refresh();pass.Restore();Check(Physics.GetIgnoreCollision(ship.m_floatCollider,fishCollider),"Pre-existing collision exclusions are preserved");Physics.IgnoreCollision(ship.m_floatCollider,fishCollider,false);
pass.Refresh();Physics.Nearby=Array.Empty<Collider>();pass.Refresh();Check(!Physics.GetIgnoreCollision(ship.m_floatCollider,fishCollider),"Fish leaving the hull area regain normal collisions");
Physics.Nearby=new[]{fishCollider};pass.Refresh();ship.m_shipControlls.User=true;typeof(FishCollisionPass).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(pass,null);Check(!Physics.GetIgnoreCollision(ship.m_floatCollider,fishCollider),"Manual takeover immediately restores fish collisions");ship.m_shipControlls.User=false;
pass.Refresh();Plugin.Instance.FishPassThrough.Value=false;typeof(FishCollisionPass).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(pass,null);Check(!Physics.GetIgnoreCollision(ship.m_floatCollider,fishCollider),"Disabling the option restores fish collisions");
Console.WriteLine($"PASS: {checks} production rock clearing, stone conservation and fish collision checks.");
