// CPU geometry export only. The production PerchedBird.cs runs unchanged against
// these small transform/mesh adapters; this is not a Unity shader/rendering test.
using N=System.Numerics;
namespace UnityEngine {
 public class Object {public static Mesh Instantiate(Mesh m)=>m.Clone();public string name;public bool destroyed;public static implicit operator bool(Object o)=>o!=null&&!o.destroyed;public static void DestroyImmediate(Object o)=>Destroy(o);public static void Destroy(Object o){if(o!=null)o.destroyed=true;}}
 public class Component:Object {public GameObject gameObject;public Transform transform=>gameObject.transform;public T GetComponentInChildren<T>()where T:Component=>gameObject.GetComponentsInChildren<T>().FirstOrDefault();public T GetComponent<T>() where T:Component=>gameObject.GetComponent<T>();}
 public class GameObject:Object {public Transform transform;public bool activeSelf=true;readonly List<Component> components=new();public GameObject(string name=""){this.name=name;transform=new Transform{gameObject=this};components.Add(transform);}public void SetActive(bool v)=>activeSelf=v;public T AddComponent<T>() where T:Component,new(){var c=new T{gameObject=this};components.Add(c);return c;}public T GetComponentInChildren<T>()where T:Component=>GetComponentsInChildren<T>().FirstOrDefault();public T GetComponent<T>()where T:Component=>components.OfType<T>().FirstOrDefault();public T[] GetComponentsInChildren<T>(bool inactive=false)where T:Component{var all=new List<T>();if(inactive||activeSelf){all.AddRange(components.OfType<T>().Where(c=>!c.destroyed));foreach(var c in transform.children)all.AddRange(c.gameObject.GetComponentsInChildren<T>(inactive));}return all.ToArray();}}
 public class Transform:Component {public Transform parent;public List<Transform> children=new();public Vector3 localPosition;public Vector3 localScale=Vector3.one;public Quaternion localRotation=Quaternion.identity;public void SetParent(Transform p,bool world){parent=p;p?.children.Add(this);}public Matrix4x4 localToWorldMatrix=>new(){Value=Matrix};public Matrix4x4 worldToLocalMatrix {get{N.Matrix4x4.Invert(Matrix,out var inverse);return new(){Value=inverse};}}public N.Matrix4x4 Matrix=>N.Matrix4x4.CreateScale(localScale.V)*N.Matrix4x4.CreateFromQuaternion(localRotation.Q)*N.Matrix4x4.CreateTranslation(localPosition.V)*(parent?.Matrix??N.Matrix4x4.Identity);public Vector3 InverseTransformPoint(Vector3 v){N.Matrix4x4.Invert(Matrix,out var inv);return Vector3.From(N.Vector3.Transform(v.V,inv));}public Vector3 TransformPoint(Vector3 v)=>Vector3.From(N.Vector3.Transform(v.V,Matrix));}
 public struct Vector2 {public static Vector2 operator +(Vector2 a,Vector2 b)=>new(a.x+b.x,a.y+b.y);public static Vector2 operator *(Vector2 a,float f)=>new(a.x*f,a.y*f);public float x,y;public Vector2(float x,float y){this.x=x;this.y=y;}}
 public struct Color32 {}
 public enum TextureFormat {RGBA32}
 public enum FilterMode {Point,Trilinear}
 public enum TextureWrapMode {Repeat}
 public struct Vector3 {public float x,y,z;public Vector3(float x,float y,float z){this.x=x;this.y=y;this.z=z;}public N.Vector3 V=>new(x,y,z);public static Vector3 From(N.Vector3 v)=>new(v.X,v.Y,v.Z);public float magnitude=>V.Length();public float sqrMagnitude=>V.LengthSquared();public Vector3 normalized=>magnitude<1e-8f?zero:From(N.Vector3.Normalize(V));public static float Dot(Vector3 a,Vector3 b)=>N.Vector3.Dot(a.V,b.V);public static Vector3 Cross(Vector3 a,Vector3 b)=>From(N.Vector3.Cross(a.V,b.V));public static Vector3 Lerp(Vector3 a,Vector3 b,float t)=>a+(b-a)*t;public static Vector3 zero=>new(0,0,0);public static Vector3 one=>new(1,1,1);public static Vector3 up=>new(0,1,0);public static Vector3 Scale(Vector3 a,Vector3 b)=>From(a.V*b.V);public static Vector3 operator +(Vector3 a,Vector3 b)=>From(a.V+b.V);public static Vector3 operator -(Vector3 a,Vector3 b)=>From(a.V-b.V);public static Vector3 operator *(Vector3 a,float b)=>From(a.V*b);}
 public struct Quaternion {public static Quaternion operator *(Quaternion a,Quaternion b)=>new(){Q=a.Q*b.Q};public static Vector3 operator *(Quaternion q,Vector3 v)=>Vector3.From(N.Vector3.Transform(v.V,q.Q));public N.Quaternion Q;public static Quaternion identity=>new(){Q=N.Quaternion.Identity};public static Quaternion Euler(float x,float y,float z)=>new(){Q=N.Quaternion.CreateFromYawPitchRoll(y*MathF.PI/180,x*MathF.PI/180,z*MathF.PI/180)};public static Quaternion Slerp(Quaternion a,Quaternion b,float t)=>new(){Q=N.Quaternion.Slerp(a.Q,b.Q,t)};public static Quaternion FromToRotation(Vector3 a,Vector3 b){var n=N.Vector3.Normalize(a.V);var m=N.Vector3.Normalize(b.V);float d=N.Vector3.Dot(n,m);return new(){Q=d<-.9999f?N.Quaternion.CreateFromAxisAngle(N.Vector3.UnitX,MathF.PI):N.Quaternion.Normalize(new N.Quaternion(N.Vector3.Cross(n,m),1+d))};}}
 public static class Mathf {public const float PI=MathF.PI;public static float InverseLerp(float a,float b,float v)=>Math.Clamp((v-a)/(b-a),0,1);public static float SmoothStep(float a,float b,float t){t=Math.Clamp(t,0,1);return a+(b-a)*t*t*(3-2*t);}public static float Lerp(float a,float b,float t)=>a+(b-a)*t;public static bool IsInfinity(float v)=>float.IsInfinity(v);public static float Min(float a,float b)=>Math.Min(a,b);public static float Abs(float v)=>Math.Abs(v);public static float MoveTowards(float a,float b,float step)=>Math.Abs(b-a)<=step?b:a+Math.Sign(b-a)*step;public static float Max(float a,float b)=>Math.Max(a,b);public static float Sin(float f)=>MathF.Sin(f);public static float Cos(float f)=>MathF.Cos(f);public static float Clamp(float f,float min,float max)=>Math.Clamp(f,min,max);}
 public struct Color {public float r,g,b,a;public Color(float r,float g,float b,float a=1){this.r=r;this.g=g;this.b=b;this.a=a;}public static Color Lerp(Color a,Color b,float t)=>new(a.r+(b.r-a.r)*t,a.g+(b.g-a.g)*t,a.b+(b.b-a.b)*t,a.a+(b.a-a.a)*t);public static Color black=>new(0,0,0);public static Color operator *(Color c,float m)=>new(c.r*m,c.g*m,c.b*m,c.a*m);}
 public static class ColorUtility {public static string ToHtmlStringRGB(Color c)=>$"{(int)(c.r*255):X2}{(int)(c.g*255):X2}{(int)(c.b*255):X2}";}
 public class Shader:Object{}
 public class Texture2D:Object {public static Texture2D whiteTexture=new();public int width=2,height=2;public FilterMode filterMode;public TextureWrapMode wrapMode;public Texture2D(){}public Texture2D(int w,int h,TextureFormat f,bool mip){}public bool LoadImage(byte[] bytes)=>false;public Color32[] GetPixels32()=>new Color32[4];public void SetPixels32(Color32[] pixels){}public void Apply(bool mip=true,bool unreadable=false){}}
 public enum MaterialGlobalIlluminationFlags {EmissiveIsBlack}
 public class Material:Object {public Shader shader;public Color color;public Material(Shader s){shader=s;}public bool HasProperty(string s)=>true;public Texture2D texture;public void SetTexture(string s,Texture2D t){texture=t;}public void SetColor(string s,Color c){}public void SetFloat(string s,float v){}public void DisableKeyword(string k){}public MaterialGlobalIlluminationFlags globalIlluminationFlags;}
 public struct Matrix4x4 {public N.Matrix4x4 Value;public static Matrix4x4 operator *(Matrix4x4 a,Matrix4x4 b)=>new(){Value=b.Value*a.Value};}
 public struct CombineInstance {public Mesh mesh;public Matrix4x4 transform;}
 public class Mesh:Object {
 public void MarkDynamic(){}public void RecalculateTangents(){}public bool isReadable=true;public int blendShapeCount;public int vertexCount=>vertices.Length;
 public Vector3[] normals=Array.Empty<Vector3>();public Color[] colors=Array.Empty<Color>();public BoneWeight[] boneWeights=Array.Empty<BoneWeight>();
 private List<int[]> subs=new(){Array.Empty<int>()};public int subMeshCount{get=>subs.Count;set{while(subs.Count<value)subs.Add(Array.Empty<int>());}}
 public int[] GetTriangles(int i)=>subs[i];public void SetTriangles(int[] t,int i){subs[i]=t;}public void SetTriangles(List<int> t,int i)=>SetTriangles(t.ToArray(),i);
 public void SetVertices(List<Vector3> v)=>vertices=v.ToArray();
 public Mesh Clone(){var m=new Mesh{vertices=(Vector3[])vertices.Clone(),normals=(Vector3[])normals.Clone(),uv=(Vector2[])uv.Clone(),colors=(Color[])colors.Clone(),boneWeights=(BoneWeight[])boneWeights.Clone(),subMeshCount=subMeshCount};for(int i=0;i<subMeshCount;i++)m.SetTriangles((int[])subs[i].Clone(),i);return m;}
public void CombineMeshes(CombineInstance[] instances,bool merge,bool matrices){var vs=new List<Vector3>();var ts=new List<int>();var tex=new List<Vector2>();foreach(var c in instances){int offset=vs.Count;vs.AddRange(c.mesh.vertices.Select(v=>Vector3.From(N.Vector3.Transform(v.V,c.transform.Value))));ts.AddRange(c.mesh.triangles.Select(i=>i+offset));tex.AddRange(c.mesh.uv);}vertices=vs.ToArray();triangles=ts.ToArray();uv=tex.ToArray();}public Vector3[] vertices;public Vector2[] uv=Array.Empty<Vector2>();public int[] triangles{get=>subs.SelectMany(t=>t).ToArray();set{subs=new(){value};}}public void RecalculateNormals(){normals=new Vector3[vertices.Length];var ts=triangles;for(int i=0;i<ts.Length;i+=3){int a=ts[i],b=ts[i+1],c=ts[i+2];var n=Vector3.Cross(vertices[b]-vertices[a],vertices[c]-vertices[a]);normals[a]+=n;normals[b]+=n;normals[c]+=n;}for(int i=0;i<normals.Length;i++)normals[i]=normals[i].normalized;}public void RecalculateBounds(){}}
 public struct BoneWeight {public int boneIndex0,boneIndex1,boneIndex2,boneIndex3;public float weight0,weight1,weight2,weight3;}
 public class MonoBehaviour:Component{}
 public class SkinnedMeshRenderer:Renderer {public Mesh sharedMesh;public Transform[] bones=Array.Empty<Transform>();public void BakeMesh(Mesh target){target.vertices=sharedMesh.vertices;}}
 public class MeshFilter:Component {public Mesh sharedMesh;}
 public class Renderer:Component {public Material sharedMaterial;public Transform probeAnchor;public bool receiveShadows;public Rendering.ShadowCastingMode shadowCastingMode;}
 public class MeshRenderer:Renderer {}
}
namespace UnityEngine.Rendering {public enum ShadowCastingMode {On}}

namespace Helmsman {internal static class GullMaterials {internal static UnityEngine.Material Create(UnityEngine.Material template,UnityEngine.Color color,float metallic)=>new UnityEngine.Material(new UnityEngine.Shader()){color=color};}}

namespace Helmsman {class Plugin{public static Plugin Instance=new();public void Record(string s){}}}
