using Helmsman;
using UnityEngine;
int passed=0;
void Check(bool value,string label){if(!value)throw new Exception(label);passed++;}
var root=new GameObject();root.activeSelf=false;var ship=root.AddComponent<Ship>();
var hull=new GameObject();hull.transform.SetParent(root.transform);var solid=hull.AddComponent<BoxCollider>();solid.size=new Vector3(3,1,8);
var terrain=new GameObject();terrain.AddComponent<Heightmap>();var obstacle=terrain.AddComponent<MeshCollider>();Physics.Nearby=new Collider[]{obstacle};
bool Clear()=>ShipLaunchClearance.Clear(ship,new Vector3(100,900,200),Quaternion.identity,out _);
Check(Clear()&&Physics.Calls>0,"Nearby terrain outside actual solids must not block launches");
Physics.Penetration=(a,b)=>.15f;
Check(!Clear(),"Actual hull/terrain intersection must block launch");
Physics.Penetration=(a,b)=>.015f;
Check(Clear(),"Tiny contact tolerance must not demand an oversized buffer");
Physics.Penetration=(a,b)=>0;
Heightmap.Ground=29.9f;Check(!Clear(),"Launch point on dry land or barely submerged ground is rejected");Heightmap.Ground=25;
ZoneSystem.instance.Loaded=p=>p.x<101;Check(!Clear(),"Unloaded hull corners reject launch even with center loaded");ZoneSystem.instance.Loaded=p=>true;
Heightmap.Available=false;Check(!Clear(),"Missing height data must reject launch");Heightmap.Available=true;
var spare=new GameObject();spare.transform.SetParent(root.transform);var spareBox=spare.AddComponent<BoxCollider>();spareBox.size=new Vector3(100,100,100);spare.activeSelf=false;
Check(Clear()&&Physics.QueryHalf.x<2,"Hidden fittings are excluded from launch bounds");
spare.activeSelf=true;spareBox.isTrigger=true;Check(Clear()&&Physics.QueryHalf.x<2,"Float and interaction triggers are excluded");spareBox.isTrigger=false;spareBox.enabled=false;Check(Clear()&&Physics.QueryHalf.x<2,"Disabled solids are excluded");
Physics.Nearby=new Collider[]{solid};Physics.Penetration=(a,b)=>1;Check(Clear(),"Prefab source colliders are ignored");
Physics.Nearby=new Collider[]{obstacle};Physics.Penetration=(a,b)=>0;
root.transform.localPosition=new Vector3(500,15,200);root.transform.localRotation=Quaternion.Euler(0,90,0);root.transform.localScale=new Vector3(2,2,2);hull.transform.localPosition=new Vector3(1,0,0);
Check(Clear()&&Math.Abs(Physics.PartPosition.x-102)<.001f&&Math.Abs(Physics.PartPosition.y-30)<.001f&&Math.Abs(Physics.PartPosition.z-200)<.001f,"Collision pose removes source translation/rotation while preserving scale");
Check(Math.Abs(Physics.QueryHalf.x-3)<.001f&&Math.Abs(Physics.QueryHalf.z-8)<.001f,"Broad-phase bounds preserve scaled hull geometry");
solid.enabled=false;Check(!Clear(),"Missing collision model never grants clearance");
spareBox.enabled=true;spare.activeSelf=false;var unknown=root.AddComponent<MeshCollider>();unknown.convex=false;
Check(!Clear()&&WaterChart.Fallback,"Unsupported concave geometry retains conservative checks");
Console.WriteLine($"PASS: {passed} launch clearance checks using production code with physics doubles; actual Unity penetration remains an in-game check.");
