using N=System.Numerics;
namespace HarmonyLib {[AttributeUsage(AttributeTargets.Class)]public class HarmonyPatch:Attribute {public HarmonyPatch(Type type,string name){}}}
namespace UnityEngine {
 public class Object {public static implicit operator bool(Object o)=>o!=null;}
 public class Component:Object {public GameObject gameObject;public Transform transform=>gameObject.transform;public T GetComponent<T>()where T:Component=>gameObject.GetComponent<T>();}
 public class MonoBehaviour:Component {}
 public class GameObject:Object {public readonly Transform transform=new();private readonly List<Component> parts=new();public T AddComponent<T>()where T:Component,new(){var c=new T{gameObject=this};parts.Add(c);return c;}public T GetComponent<T>()where T:Component=>parts.OfType<T>().FirstOrDefault();}
 public class BoxCollider {public Vector3 size;}
 public class Transform:Object {public Vector3 localScale=new(1,1,1);public Quaternion rotation=Quaternion.identity;public Vector3 up=>rotation*new Vector3(0,1,0);public Vector3 forward=>rotation*new Vector3(0,0,1);}
 public struct Vector2 {public float x,y;public Vector2(float x,float y){this.x=x;this.y=y;}}
 public struct Vector3 {public float x,y,z;public Vector3(float x,float y,float z){this.x=x;this.y=y;this.z=z;}internal N.Vector3 N=>new(x,y,z);internal static Vector3 From(N.Vector3 v)=>new(v.X,v.Y,v.Z);public float sqrMagnitude=>N.LengthSquared();public static Vector3 Cross(Vector3 a,Vector3 b)=>From(System.Numerics.Vector3.Cross(a.N,b.N));public static float Dot(Vector3 a,Vector3 b)=>System.Numerics.Vector3.Dot(a.N,b.N);public static Vector3 Lerp(Vector3 a,Vector3 b,float t)=>From(System.Numerics.Vector3.Lerp(a.N,b.N,Math.Clamp(t,0,1)));public static Vector3 Normalize(Vector3 v)=>v.sqrMagnitude>1e-9?From(System.Numerics.Vector3.Normalize(v.N)):new();public static Vector3 operator +(Vector3 a,Vector3 b)=>From(a.N+b.N);public static Vector3 operator *(Vector3 a,float b)=>From(a.N*b);public static Vector3 operator -(Vector3 a)=>From(-a.N);public static Vector3 operator -(Vector3 a,Vector3 b)=>From(a.N-b.N);}
 public struct Quaternion {public N.Quaternion Q;public static Quaternion identity=>new(){Q=N.Quaternion.Identity};public static Vector3 operator *(Quaternion a,Vector3 b)=>Vector3.From(N.Vector3.Transform(b.N,a.Q));public static Quaternion LookRotation(Vector3 forward,Vector3 up){var z=Vector3.Normalize(forward).N;var x=N.Vector3.Normalize(N.Vector3.Cross(up.N,z));var y=N.Vector3.Cross(z,x);return new(){Q=N.Quaternion.CreateFromRotationMatrix(new(x.X,x.Y,x.Z,0,y.X,y.Y,y.Z,0,z.X,z.Y,z.Z,0,0,0,0,1))};}public static Quaternion RotateTowards(Quaternion a,Quaternion b,float angle){float dot=Math.Abs(N.Quaternion.Dot(a.Q,b.Q));float degrees=2*MathF.Acos(Math.Clamp(dot,0,1))*180/MathF.PI;return new(){Q=N.Quaternion.Slerp(a.Q,b.Q,degrees<.001f?1:Math.Min(1,angle/degrees))};}}
 public static class Mathf {public const float PI=MathF.PI;public static float Clamp(float v,float a,float b)=>Math.Clamp(v,a,b);public static float Sin(float v)=>MathF.Sin(v);public static float Clamp01(float v)=>Math.Clamp(v,0,1);public static float Min(float a,float b)=>Math.Min(a,b);public static float Max(float a,float b)=>Math.Max(a,b);public static float Abs(float v)=>Math.Abs(v);public static float MoveTowards(float a,float b,float d)=>Math.Abs(b-a)<=d?b:a+Math.Sign(b-a)*d;}
}
public class Ship:UnityEngine.MonoBehaviour {public enum Speed {Stop,Back,Slow,Half,Full}public UnityEngine.BoxCollider m_floatCollider=new();public float m_sailForceOffset=1,m_angularDamping=.05f;public Speed Setting;public bool m_hasSail=true;public UnityEngine.GameObject m_sailObject,m_mastObject;public Speed GetSpeedSetting()=>Setting;}
public class EnvMan:UnityEngine.Object {public static EnvMan instance=new();public UnityEngine.Vector3 Wind=new(1,0,0);public UnityEngine.Vector3 GetWindDir()=>Wind;}
