<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><Nullable>annotations</Nullable><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../../src/Helmsman/Art/PerchedBird.cs" Link="PerchedBird.cs" /></ItemGroup></Project>
