// CPU geometry export only. The production PerchedBird.cs runs unchanged against
// these small transform/mesh adapters; this is not a Unity shader/rendering test.
using N=System.Numerics;
namespace UnityEngine {
 public class Object {public string name;public bool destroyed;public static implicit operator bool(Object o)=>o!=null&&!o.destroyed;public static void DestroyImmediate(Object o)=>Destroy(o);public static void Destroy(Object o){if(o!=null)o.destroyed=true;}}
 public class Component:Object {public GameObject gameObject;public Transform transform=>gameObject.transform;public T GetComponent<T>() where T:Component=>gameObject.GetComponent<T>();}
 public class GameObject:Object {public Transform transform;public bool activeSelf=true;readonly List<Component> components=new();public GameObject(string name=""){this.name=name;transform=new Transform{gameObject=this};components.Add(transform);}public void SetActive(bool v)=>activeSelf=v;public T AddComponent<T>() where T:Component,new(){var c=new T{gameObject=this};components.Add(c);return c;}public T GetComponent<T>()where T:Component=>components.OfType<T>().FirstOrDefault();public T[] GetComponentsInChildren<T>(bool inactive=false)where T:Component{var all=new List<T>();if(inactive||activeSelf){all.AddRange(components.OfType<T>().Where(c=>!c.destroyed));foreach(var c in transform.children)all.AddRange(c.gameObject.GetComponentsInChildren<T>(inactive));}return all.ToArray();}}
 public class Transform:Component {public Transform parent;public List<Transform> children=new();public Vector3 localPosition;public Vector3 localScale=Vector3.one;public Quaternion localRotation=Quaternion.identity;public void SetParent(Transform p,bool world){parent=p;p?.children.Add(this);}public Matrix4x4 localToWorldMatrix=>new(){Value=Matrix};public Matrix4x4 worldToLocalMatrix {get{N.Matrix4x4.Invert(Matrix,out var inverse);return new(){Value=inverse};}}public N.Matrix4x4 Matrix=>N.Matrix4x4.CreateScale(localScale.V)*N.Matrix4x4.CreateFromQuaternion(localRotation.Q)*N.Matrix4x4.CreateTranslation(localPosition.V)*(parent?.Matrix??N.Matrix4x4.Identity);public Vector3 TransformPoint(Vector3 v)=>Vector3.From(N.Vector3.Transform(v.V,Matrix));}
 public struct Vector2 {public float x,y;public Vector2(float x,float y){this.x=x;this.y=y;}}
 public struct Color32 {}
 public enum TextureFormat {RGBA32}
 public enum FilterMode {Point}
 public enum TextureWrapMode {Repeat}
 public struct Vector3 {public float x,y,z;public Vector3(float x,float y,float z){this.x=x;this.y=y;this.z=z;}public N.Vector3 V=>new(x,y,z);public static Vector3 From(N.Vector3 v)=>new(v.X,v.Y,v.Z);public float magnitude=>V.Length();public static Vector3 zero=>new(0,0,0);public static Vector3 one=>new(1,1,1);public static Vector3 up=>new(0,1,0);public static Vector3 Scale(Vector3 a,Vector3 b)=>From(a.V*b.V);public static Vector3 operator +(Vector3 a,Vector3 b)=>From(a.V+b.V);public static Vector3 operator -(Vector3 a,Vector3 b)=>From(a.V-b.V);public static Vector3 operator *(Vector3 a,float b)=>From(a.V*b);}
 public struct Quaternion {public static Quaternion operator *(Quaternion a,Quaternion b)=>new(){Q=a.Q*b.Q};public N.Quaternion Q;public static Quaternion identity=>new(){Q=N.Quaternion.Identity};public static Quaternion Euler(float x,float y,float z)=>new(){Q=N.Quaternion.CreateFromYawPitchRoll(y*MathF.PI/180,x*MathF.PI/180,z*MathF.PI/180)};public static Quaternion Slerp(Quaternion a,Quaternion b,float t)=>new(){Q=N.Quaternion.Slerp(a.Q,b.Q,t)};public static Quaternion FromToRotation(Vector3 a,Vector3 b){var n=N.Vector3.Normalize(a.V);var m=N.Vector3.Normalize(b.V);float d=N.Vector3.Dot(n,m);return new(){Q=d<-.9999f?N.Quaternion.CreateFromAxisAngle(N.Vector3.UnitX,MathF.PI):N.Quaternion.Normalize(new N.Quaternion(N.Vector3.Cross(n,m),1+d))};}}
 public static class Mathf {public const float PI=MathF.PI;public static float Abs(float v)=>Math.Abs(v);public static float MoveTowards(float a,float b,float step)=>Math.Abs(b-a)<=step?b:a+Math.Sign(b-a)*step;public static float Max(float a,float b)=>Math.Max(a,b);public static float Sin(float f)=>MathF.Sin(f);public static float Cos(float f)=>MathF.Cos(f);public static float Clamp(float f,float min,float max)=>Math.Clamp(f,min,max);}
 public struct Color {public float r,g,b,a;public Color(float r,float g,float b,float a=1){this.r=r;this.g=g;this.b=b;this.a=a;}public static Color black=>new(0,0,0);public static Color operator *(Color c,float m)=>new(c.r*m,c.g*m,c.b*m,c.a*m);}
 public static class ColorUtility {public static string ToHtmlStringRGB(Color c)=>$"{(int)(c.r*255):X2}{(int)(c.g*255):X2}{(int)(c.b*255):X2}";}
 public class Shader:Object{}
 public class Texture2D:Object {public static Texture2D whiteTexture=new();public int width=2,height=2;public FilterMode filterMode;public TextureWrapMode wrapMode;public Texture2D(){}public Texture2D(int w,int h,TextureFormat f,bool mip){}public bool LoadImage(byte[] bytes)=>false;public Color32[] GetPixels32()=>new Color32[4];public void SetPixels32(Color32[] pixels){}public void Apply(){}}
 public enum MaterialGlobalIlluminationFlags {EmissiveIsBlack}
 public class Material:Object {public Shader shader;public Color color;public Material(Shader s){shader=s;}public bool HasProperty(string s)=>true;public void SetTexture(string s,Texture2D t){}public void SetColor(string s,Color c){}public void SetFloat(string s,float v){}public void DisableKeyword(string k){}public MaterialGlobalIlluminationFlags globalIlluminationFlags;}
 public struct Matrix4x4 {public N.Matrix4x4 Value;public static Matrix4x4 operator *(Matrix4x4 a,Matrix4x4 b)=>new(){Value=b.Value*a.Value};}
 public struct CombineInstance {public Mesh mesh;public Matrix4x4 transform;}
 public class Mesh:Object {public void CombineMeshes(CombineInstance[] instances,bool merge,bool matrices){var vs=new List<Vector3>();var ts=new List<int>();foreach(var c in instances){int offset=vs.Count;vs.AddRange(c.mesh.vertices.Select(v=>Vector3.From(N.Vector3.Transform(v.V,c.transform.Value))));ts.AddRange(c.mesh.triangles.Select(i=>i+offset));}vertices=vs.ToArray();triangles=ts.ToArray();}public Vector3[] vertices;public Vector2[] uv;public int[] triangles;public void RecalculateNormals(){}public void RecalculateBounds(){}}
 public class MeshFilter:Component {public Mesh sharedMesh;}
 public class Renderer:Component {public Material sharedMaterial;public Transform probeAnchor;public bool receiveShadows;public Rendering.ShadowCastingMode shadowCastingMode;}
 public class MeshRenderer:Renderer {}
}
namespace UnityEngine.Rendering {public enum ShadowCastingMode {On}}
