using Helmsman;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
int checks=0;void Check(bool ok,string why){checks++;if(!ok)throw new Exception(why);}
Image Art()=>new(){sprite=new Sprite(),material=new Material(),type=Image.Type.Sliced,pixelsPerUnitMultiplier=2,fillCenter=true,color=new Color(.8f,.7f,.6f)};
TMP_Text Label()=>new(){font=new TMP_FontAsset(),fontSharedMaterial=new Material(),fontStyle=3,color=new Color(1,.6f,.2f)};
var text=Label();var button=new Button{targetGraphic=Art(),transition=Selectable.Transition.SpriteSwap,spriteState=new(){selectedSprite=new Sprite(),highlightedSprite=new Sprite()}};button.children[typeof(TMP_Text)]=text;
var board=Art();var bg=new Transform();bg.children[typeof(Image)]=board;
var field=new TMP_InputField{targetGraphic=Art(),transition=Selectable.Transition.SpriteSwap,customCaretColor=true,selectionColor=new Color(.3f,.2f,.1f)};
var split=new Component();split.children[typeof(TMP_InputField)]=field;
var gui=new InventoryGui{m_player=new(){background=bg},m_stackAllButton=button,m_tabCraft=button,m_recipeDecription=Label(),m_containerName=Label(),m_splitDialog=split,m_pvp=new(){targetGraphic=Art(),graphic=Art()}};
NativeMenuTheme.Capture(gui);
var panel=new Image();NativeMenuTheme.Panel(panel);Check(panel.sprite==board.sprite&&panel.material==board.material&&panel.type==Image.Type.Sliced,"panel borrows native artwork and slice mode");
var target=new Button{targetGraphic=new Image(),interactable=false};var targetText=new TMP_Text();target.children[typeof(TMP_Text)]=targetText;int callbacks=0;target.onClick=()=>callbacks++;button.onClick=()=>throw new Exception("native callback leaked");
NativeMenuTheme.Button(target);target.onClick();Check(callbacks==1&&!target.interactable,"styling preserves own callbacks and disabled state");
Check(target.transition==Selectable.Transition.SpriteSwap&&((Image)target.targetGraphic).sprite==((Image)button.targetGraphic).sprite&&target.spriteState.selectedSprite==button.spriteState.selectedSprite,"button uses native sprites and transitions");
Check(target.navigation.mode==Navigation.Mode.None,"custom controller navigation remains authoritative");
Check(targetText.font==text.font&&targetText.fontSharedMaterial==text.fontSharedMaterial,"button borrows native font and outline material");
var body=new TMP_Text();NativeMenuTheme.Text(body);Check(body.font==gui.m_recipeDecription.font,"body uses native description font");NativeMenuTheme.Text(body,true);Check(body.font==gui.m_containerName.font,"heading uses native container title font");
var original=((Image)button.targetGraphic).sprite;NativeMenuTheme.ActiveTab(target);Check(((Image)target.targetGraphic).sprite==button.spriteState.selectedSprite&&((Image)button.targetGraphic).sprite==original,"active tab changes only Helmsman artwork");
var customInput=new TMP_InputField{targetGraphic=new Image(),interactable=false};int submits=0;customInput.onSubmit=()=>submits++;NativeMenuTheme.Input(customInput);customInput.onSubmit();Check(submits==1&&!customInput.interactable&&customInput.customCaretColor,"input styling preserves save handler and permission state");
Check(((Image)customInput.targetGraphic).sprite==((Image)field.targetGraphic).sprite,"input borrows native field image");
var box=new Image();var marker=new Image();Check(NativeMenuTheme.Checkmark(box,marker)&&!box.raycastTarget&&!marker.raycastTarget,"checkbox visuals do not intercept button clicks");
button.transition=Selectable.Transition.Animation;NativeMenuTheme.Button(target);Check(target.transition==Selectable.Transition.ColorTint,"native animator state is not copied without animator");
NativeMenuTheme.Clear();var fallback=new Image();NativeMenuTheme.Panel(fallback);Check(fallback.color.a>.9f,"missing native theme retains readable fallback");
NativeMenuTheme.Capture(null);NativeMenuTheme.Button(target);NativeMenuTheme.Input(customInput);Check(!NativeMenuTheme.Checkmark(box,marker),"missing GUI lifecycle is safe");
var newBoard=Art();var newBg=new Transform();newBg.children[typeof(Image)]=newBoard;gui=new InventoryGui{m_player=new(){background=newBg},m_stackAllButton=button,m_containerName=Label(),m_recipeDecription=Label()};NativeMenuTheme.Capture(gui);NativeMenuTheme.Panel(panel);Check(panel.sprite==newBoard.sprite,"scene reload borrows new instance assets");
Console.WriteLine($"PASS: {checks} native menu theme and interaction isolation checks.");
